// Resources
// =====
export const ADD_RESOURCE = 'ADD_RESOURCE'
export const ADD_RESOURCE_REQUEST = 'ADD_RESOURCE_REQUEST'
export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS'
export const ADD_RESOURCE_FAILURE = 'ADD_RESOURCE_FAILURE'

// Lists
// =====
export const ADD_LIST = 'ADD_LIST'
export const ADD_LIST_REQUEST = 'ADD_LIST_REQUEST'
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS'
export const ADD_LIST_FAILURE = 'ADD_LIST_FAILURE'

// Dashboards
// ==========
export const ADD_DASHBOARD = 'ADD_DASHBOARD'
export const ADD_DASHBOARD_REQUEST = 'ADD_DASHBOARD_REQUEST'
export const ADD_DASHBOARD_SUCCESS = 'ADD_DASHBOARD_SUCCESS'
export const ADD_DASHBOARD_FAILURE = 'ADD_DASHBOARD_FAILURE'
export const SET_CURRENT_DASHBOARD = 'SET_CURRENT_DASHBOARD'
export const SET_CURRENT_INPUT_TYPE = 'SET_CURRENT_INPUT_TYPE'
