// Utility
// =======
export const LOAD_DATA = 'LOAD_DATA'
export const CLEAR_DATA = 'CLEAR_DATA'

// Dashboards
// ==========
export const CREATE_DASHBOARD = 'CREATE_DASHBOARD'
export const CREATE_DASHBOARD_REQUEST = 'CREATE_DASHBOARD_REQUEST'
export const CREATE_DASHBOARD_SUCCESS = 'CREATE_DASHBOARD_SUCCESS'
export const CREATE_DASHBOARD_FAILURE = 'CREATE_DASHBOARD_FAILURE'
export const SET_CURRENT_DASHBOARD = 'SET_CURRENT_DASHBOARD'

// Lists
// =====
export const CREATE_LIST = 'CREATE_LIST'
export const CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST'
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS'
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE'
export const SET_CURRENT_LIST = 'SET_CURRENT_LIST'

// Resources
// =========
export const CREATE_RESOURCE = 'CREATE_RESOURCE'
export const CREATE_RESOURCE_REQUEST = 'CREATE_RESOURCE_REQUEST'
export const CREATE_RESOURCE_SUCCESS = 'CREATE_RESOURCE_SUCCESS'
export const CREATE_RESOURCE_FAILURE = 'CREATE_RESOURCE_FAILURE'

// Input Types
// ===========
export const SET_CURRENT_INPUT_TYPE = 'SET_CURRENT_INPUT_TYPE'

// Users
// =====
// Auth
// ----
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'
// Dashboards
// ----------
export const ADD_DASHBOARD_TO_USER = 'ADD_DASHBOARD_TO_USER'
export const ADD_DASHBOARD_TO_USER_REQUEST = 'ADD_DASHBOARD_TO_USER_REQUEST'
export const ADD_DASHBOARD_TO_USER_SUCCESS = 'ADD_DASHBOARD_TO_USER_SUCCESS'
export const ADD_DASHBOARD_TO_USER_FAILURE = 'ADD_DASHBOARD_TO_USER_FAILURE'
