// Resources
// =====
export const ADD_RESOURCE = 'ADD_RESOURCE';
export const ADD_RESOURCE_REQUEST = 'ADD_RESOURCE_REQUEST';
export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS';
export const ADD_RESOURCE_FAILURE = 'ADD_RESOURCE_FAILURE';

export const COMPLETE_RESOURCE = 'COMPLETE_RESOURCE';

// Lists
// =====
export const ADD_LIST = 'ADD_LIST';
export const ADD_LIST_REQUEST = 'ADD_LIST_REQUEST';
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const ADD_LIST_FAILURE = 'ADD_LIST_FAILURE';
